# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40d585c65772c6e50258d22ba65172383dbabddea74d06c365d0b6182fe6b3faee0ad5ffeca7bdb3b02ff07ba32f06b0755dca47ea1a897fd0ec2829066f09aa

test:
  secret_key_base: 5ce42335e4ad7ef92e8d7b50cccd529ab50742b0c82d8ee98472c5ed3a2d0cee2759fd97c969cf27761ea977aab903bb97db5b58d4ffe1ac921776bb82c99f9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
